"""
Merge fold files generated by multiple batch runs.

Batch mode generates files with window suffixes, such as Ridge_fold_0-10.csv and Ridge_fold_11-20.csv.
This script merges those files into one complete CSV, equivalent to the output of a full non-batch run.

Usage:
1. Set MODEL_LABEL at the top of this file.
2. Run: python merge.py
3. The script automatically finds and merges matching fold files in out/.
"""

import os
import pandas as pd
from glob import glob
import re

# ========== GLOBAL CONFIGURATION ==========
MODEL_LABEL = 'SGD-Modified_Huber-b'  # Model label

# ========== PATH CONFIGURATION ==========
PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))
OUTPUT_DIR = os.path.join(PROJECT_ROOT, 'out')

def merge_fold_files(model_label: str, output_dir: str):
    """
    Merge all fold files generated by batch runs.
    
    Args:
        model_label: Model label (e.g., 'Ridge').
        output_dir: Output directory.
    """
    print(f"\n==================== MERGE FOLD FILES ====================\n")
    print(f"Model Label: {model_label}")
    print(f"Output Directory: {output_dir}\n")
    
    # Find only batch files with window suffixes, e.g., MODEL_LABEL_fold_0-10.csv
    # Exclude files without suffixes from non-batch runs
    pattern = os.path.join(output_dir, f"{model_label}_fold_*.csv")
    
    # Retain only files matching MODEL_LABEL_fold_<start>-<end>.csv
    all_files = []
    for filepath in glob(pattern):
        basename = os.path.basename(filepath)
        # Check for the pattern MODEL_LABEL_fold_<start>-<end>.csv
        if re.match(rf"{model_label}_fold_\d+-\d+\.csv", basename):
            all_files.append(filepath)
    
    if not all_files:
        print(f"[ERROR] No batch mode files found (with window suffix): {model_label}_fold_*.csv")
        print(f"Please check MODEL_LABEL setting and output directory: {output_dir}")
        print(f"Note: merge.py only processes batch mode generated files (e.g., {model_label}_fold_0-10.csv)")
        return
    
    print(f"[INFO] Found {len(all_files)} files:")
    for f in sorted(all_files):
        print(f"  - {os.path.basename(f)}")
    
    # Read and merge all files
    all_dataframes = []
    for filepath in sorted(all_files):
        try:
            df = pd.read_csv(filepath)
            print(f"[INFO] Reading: {os.path.basename(filepath)} ({len(df)} rows)")
            all_dataframes.append(df)
        except Exception as e:
            print(f"[WARN] Failed to read file {os.path.basename(filepath)}: {e}")
            continue
    
    if not all_dataframes:
        print(f"[ERROR] No files were successfully read")
        return
    
    # Concatenate all DataFrames
    merged_df = pd.concat(all_dataframes, ignore_index=True)
    
    # Sort by Idx if the column exists
    if 'Idx' in merged_df.columns:
        merged_df = merged_df.sort_values('Idx').reset_index(drop=True)
    
    # Save the merged file
    output_file = os.path.join(output_dir, f"{model_label}_fold.csv")
    merged_df.to_csv(output_file, index=False)
    
    print(f"\n[SUCCESS] Merge completed!")
    print(f"  Total rows: {len(merged_df)}")
    print(f"  Output file: {output_file}")
    
    return output_file


def merge_importance_files(model_label: str, output_dir: str, methods: list = None):
    """
    Merge all importance fold files generated by batch runs.
    
    Args:
        model_label: Model label.
        output_dir: Output directory.
        methods: Importance methods (e.g., ['coefficient', 'permutation']).
                If None, automatically detect all methods.
    """
    print(f"\n==================== MERGE IMPORTANCE FILES ====================\n")
    
    if methods is None:
        # Automatically detect all methods
        # Find only batch files matching MODEL_LABEL_imp_*_fold_<start>-<end>.csv
        pattern = os.path.join(output_dir, f"{model_label}_imp_*_fold_*.csv")
        files = glob(pattern)
        
        # Extract method names from filenames with window suffixes
        methods = set()
        for filepath in files:
            basename = os.path.basename(filepath)
            # Match MODEL_LABEL_imp_{method}_fold_<start>-<end>.csv
            match = re.match(rf"{model_label}_imp_([^_]+)_fold_\d+-\d+\.csv", basename)
            if match:
                methods.add(match.group(1))
        methods = sorted(list(methods))
    
    if not methods:
        print(f"[WARN] No importance files found or unable to detect methods")
        return
    
    print(f"[INFO] Detected methods: {', '.join(methods)}")
    
    for method in methods:
        # Find only batch files with window suffixes
        pattern = os.path.join(output_dir, f"{model_label}_imp_{method}_fold_*.csv")
        all_matching_files = glob(pattern)
        
        # Retain only files with window suffixes
        files = []
        for filepath in all_matching_files:
            basename = os.path.basename(filepath)
            # Check for the pattern MODEL_LABEL_imp_{method}_fold_<start>-<end>.csv
            if re.match(rf"{model_label}_imp_{method}_fold_\d+-\d+\.csv", basename):
                files.append(filepath)
        files = sorted(files)
        
        if not files:
            print(f"[WARN] No files found for method {method}")
            continue
        
        print(f"\n[INFO] Merging files for method {method} ({len(files)} files):")
        for f in files:
            print(f"  - {os.path.basename(f)}")
        
        # Read and concatenate
        all_dataframes = []
        for filepath in files:
            try:
                df = pd.read_csv(filepath)
                print(f"  [INFO] Reading: {os.path.basename(filepath)} ({len(df)} rows)")
                all_dataframes.append(df)
            except Exception as e:
                print(f"  [WARN] Failed to read file {os.path.basename(filepath)}: {e}")
                continue
        
        if not all_dataframes:
            print(f"  [WARN] No files were successfully read for method {method}")
            continue
        
        # Concatenate
        merged_df = pd.concat(all_dataframes, ignore_index=True)
        
        # Sort by Idx if the column exists
        if 'Idx' in merged_df.columns:
            merged_df = merged_df.sort_values('Idx').reset_index(drop=True)
        
        # Save the merged file
        output_file = os.path.join(output_dir, f"{model_label}_imp_{method}_fold.csv")
        merged_df.to_csv(output_file, index=False)
        
        print(f"  [SUCCESS] Merge completed: {output_file} ({len(merged_df)} rows)")


def main():
    """Main entry point."""
    print(f"\n{'='*60}")
    print(f"Merge Batch Files for {MODEL_LABEL}")
    print(f"{'='*60}\n")
    
    # Merge fold files
    merge_fold_files(MODEL_LABEL, OUTPUT_DIR)
    
    # Merge importance files
    merge_importance_files(MODEL_LABEL, OUTPUT_DIR)
    
    print(f"\n{'='*60}")
    print(f"All merge operations completed!")
    print(f"{'='*60}\n")


if __name__ == '__main__':
    main()

