"""
Generate summary files.

In batch mode, the program generates fold files without summary files.
This script generates summaries from merged fold files, equivalent to those from non-batch runs.

Usage:
1. Set MODEL_LABEL at the top of this file.
2. Run merge.py first to generate the merged fold files.
3. Run: python summary.py
"""

import os
import pandas as pd
import numpy as np
from glob import glob
import re

# ========== GLOBAL CONFIGURATION ==========
MODEL_LABEL = 'SGD-Modified_Huber-b'  # Model label

# ========== PATH CONFIGURATION ==========
PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))
OUTPUT_DIR = os.path.join(PROJECT_ROOT, 'out')

# ========== IMPORTANCE METHOD CONFIGURATION ==========
IMPORTANCE_METHODS = None  # For example: ['coefficient', 'permutation', 'shap']

# ========== OTHER CONFIGURATION ==========
GENERATE_CROSS_METHOD_SUMMARY = False  # Whether to generate an importance summary across methods
CROSS_METHOD_SUMMARY_SUFFIX = '_imp_sum'  # Filename suffix for the summary across methods


def summarize_kfold_results(metrics_list: list, model_label: str) -> pd.DataFrame:
    """
    Generate summary statistics from fold metrics, computing means only.
    
    Args:
        metrics_list: List of metric dictionaries for all folds.
        model_label: Model label.
    
    Returns:
        Summary DataFrame containing Model and the mean of each metric.
    """
    if not metrics_list:
        return pd.DataFrame([{'Model': model_label}])
    
    df = pd.DataFrame(metrics_list)
    
    # Compute means of numeric columns only
    summary = df.mean(numeric_only=True)
    
    # Build the final result using only the specified columns
    final_result = {
        'Model': model_label,
        'Accuracy': summary.get('Accuracy'),
        'Precision_1': summary.get('Precision_1'),
        'Recall_1': summary.get('Recall_1'),
        'F1_1': summary.get('F1_1'),
        'Precision_0': summary.get('Precision_0'),
        'Recall_0': summary.get('Recall_0'),
        'F1_0': summary.get('F1_0'),
        'AUC': summary.get('AUC'),
    }
    
    return pd.DataFrame([final_result])


def generate_fold_summary(model_label: str, output_dir: str):
    """
    Generate summaries from merged fold files without window suffixes.
    
    Args:
        model_label: Model label.
        output_dir: Output directory.
    """
    print(f"\n==================== GENERATE FOLD SUMMARY ====================\n")
    
    # Process only files without window suffixes, as generated by merge.py
    fold_file = os.path.join(output_dir, f"{model_label}_fold.csv")
    
    if not os.path.exists(fold_file):
        print(f"[ERROR] Merged fold file not found: {fold_file}")
        print(f"Please run merge.py first to generate the merged fold file")
        print(f"Note: summary.py only processes files without window suffix (merged files)")
        return
    
    print(f"[INFO] Reading fold file: {fold_file}")
    df = pd.read_csv(fold_file)
    print(f"[INFO] Total rows: {len(df)}")
    
    # Convert to a list of metric dictionaries
    metrics_list = df.to_dict('records')
    
    # Generate the summary
    summary_df = summarize_kfold_results(metrics_list, model_label)
    
    # Save the summary file
    summary_file = os.path.join(output_dir, f"{model_label}_sum.csv")
    summary_df.to_csv(summary_file, index=False)
    
    print(f"[SUCCESS] Summary file generated: {summary_file}")
    print(f"  Summary statistics:")
    print(summary_df.to_string(index=False))


def generate_importance_summary(imp_csv_path: str, summary_csv_path: str) -> str:
    """
    Generate summary statistics from an importance fold file.
    
    Args:
        imp_csv_path: Input importance fold file path.
        summary_csv_path: Output summary statistics file path.
    
    Returns:
        Summary statistics file path.
    """
    # Ensure the output directory exists
    os.makedirs(os.path.dirname(summary_csv_path), exist_ok=True)
    
    # Read importance fold data
    if not os.path.exists(imp_csv_path):
        raise FileNotFoundError(f"Importance fold file not found: {imp_csv_path}")
    
    df_imp = pd.read_csv(imp_csv_path)
    
    # Get all feature columns except Idx
    feature_cols = [col for col in df_imp.columns if col != 'Idx']
    
    # Compute statistics for each feature
    summary_data = []
    for feature in feature_cols:
        values = df_imp[feature].values
        summary_data.append({
            'feature': feature,
            'mean': np.mean(values),
            'std': np.std(values),
            'med': np.median(values),
            'min': np.min(values),
            'max': np.max(values)
        })
    
    # Create the summary DataFrame
    df_summary = pd.DataFrame(summary_data)
    
    # Sort by mean in descending order
    df_summary = df_summary.sort_values('mean', ascending=False).reset_index(drop=True)
    
    # Save the summary file
    df_summary.to_csv(summary_csv_path, index=False)
    
    return summary_csv_path


def generate_multiple_importance_summary(
    output_dir: str,
    model_label: str,
    methods: list = None
) -> None:
    """
    Generate summary files for multiple importance methods.
    
    Args:
        output_dir: Output directory.
        model_label: Model label.
        methods: Importance methods; detect automatically if None.
    """
    print(f"\n==================== GENERATE IMPORTANCE SUMMARY ====================\n")
    
    if methods is None:
        # Detect all methods from files without window suffixes
        pattern = os.path.join(output_dir, f"{model_label}_imp_*_fold.csv")
        all_files = glob(pattern)
        
        # Retain only files without window suffixes, as generated by merge.py
        files = []
        for filepath in all_files:
            basename = os.path.basename(filepath)
            # Match only files without window suffixes: MODEL_LABEL_imp_{method}_fold.csv
            # Exclude files with window suffixes: MODEL_LABEL_imp_{method}_fold_<start>-<end>.csv
            if re.match(rf"{model_label}_imp_([^_]+)_fold\.csv$", basename):
                files.append(filepath)
        
        methods = set()
        for filepath in files:
            basename = os.path.basename(filepath)
            match = re.match(rf"{model_label}_imp_([^_]+)_fold\.csv", basename)
            if match:
                methods.add(match.group(1))
        methods = sorted(list(methods))
    
    if not methods:
        print(f"[WARN] No importance fold files found or unable to detect methods")
        return
    
    print(f"[INFO] Detected methods: {', '.join(methods)}")
    
    for method in methods:
        imp_fold_path = os.path.join(output_dir, f"{model_label}_imp_{method}_fold.csv")
        imp_sum_path = os.path.join(output_dir, f"{model_label}_imp_{method}_sum.csv")
        
        if os.path.exists(imp_fold_path):
            try:
                generate_importance_summary(imp_fold_path, imp_sum_path)
                print(f"[SUCCESS] {method.upper()} importance summary: {os.path.basename(imp_sum_path)}")
            except Exception as e:
                print(f"[WARN] Failed to generate {method} importance summary: {e}")
        else:
            print(f"[WARN] {method} importance fold file not found: {imp_fold_path}")


def generate_cross_method_importance_summary(
    output_dir: str,
    model_label: str,
    methods: list = None,
    cross_method_suffix: str = '_imp_sum'
) -> None:
    """
    Generate an importance summary across methods.
    
    Args:
        output_dir: Output directory.
        model_label: Model label.
        methods: List of importance methods.
        cross_method_suffix: Filename suffix for the summary across methods.
    """
    print(f"\n==================== GENERATE CROSS-METHOD SUMMARY ====================\n")
    
    if methods is None:
        # Detect methods from summary files, which should already exist
        pattern = os.path.join(output_dir, f"{model_label}_imp_*_sum.csv")
        all_files = glob(pattern)
        
        # Retain only summary files without window suffixes
        files = []
        for filepath in all_files:
            basename = os.path.basename(filepath)
            # Match only files without window suffixes: MODEL_LABEL_imp_{method}_sum.csv
            if re.match(rf"{model_label}_imp_([^_]+)_sum\.csv$", basename):
                files.append(filepath)
        
        methods = set()
        for filepath in files:
            basename = os.path.basename(filepath)
            match = re.match(rf"{model_label}_imp_([^_]+)_sum\.csv", basename)
            if match:
                methods.add(match.group(1))
        methods = sorted(list(methods))
    
    if not methods:
        print(f"[WARN] No importance summary files found")
        return
    
    # Read summary files for all methods
    method_summaries = {}
    for method in methods:
        summary_path = os.path.join(output_dir, f"{model_label}_imp_{method}_sum.csv")
        
        if os.path.exists(summary_path):
            try:
                df_summary = pd.read_csv(summary_path)
                # Extract the mean column as the importance for this method
                method_summaries[method] = df_summary.set_index('feature')['mean'].to_dict()
                print(f"[INFO] Reading {method} summary: {len(method_summaries[method])} features")
            except Exception as e:
                print(f"[WARN] Failed to read {method} summary: {e}")
        else:
            print(f"[WARN] {method} summary file not found: {summary_path}")
    
    if not method_summaries:
        print(f"[WARN] No method summaries found, skipping cross-method summary")
        return
    
    # Get all features
    all_features = set()
    for method_data in method_summaries.values():
        all_features.update(method_data.keys())
    all_features = sorted(list(all_features))
    
    # Create the DataFrame summarizing all methods
    cross_method_data = {'feature': all_features}
    for method, method_data in method_summaries.items():
        cross_method_data[method] = [method_data.get(feature, 0.0) for feature in all_features]
    
    df_cross_method = pd.DataFrame(cross_method_data)
    
    # Save the summary across methods
    cross_method_path = os.path.join(output_dir, f"{model_label}{cross_method_suffix}.csv")
    df_cross_method.to_csv(cross_method_path, index=False)
    
    print(f"[SUCCESS] Cross-method importance summary: {os.path.basename(cross_method_path)}")


def main():
    """Main entry point."""
    print(f"\n{'='*60}")
    print(f"Generate Summary Files for {MODEL_LABEL}")
    print(f"{'='*60}\n")
    
    # Generate the fold summary
    generate_fold_summary(MODEL_LABEL, OUTPUT_DIR)
    
    # Generate the importance summary
    generate_multiple_importance_summary(
        OUTPUT_DIR,
        MODEL_LABEL,
        methods=IMPORTANCE_METHODS
    )
    
    # Generate the importance summary across methods
    if GENERATE_CROSS_METHOD_SUMMARY:
        generate_cross_method_importance_summary(
            OUTPUT_DIR,
            MODEL_LABEL,
            methods=IMPORTANCE_METHODS,
            cross_method_suffix=CROSS_METHOD_SUMMARY_SUFFIX
        )
    
    print(f"\n{'='*60}")
    print(f"All summary operations completed!")
    print(f"{'='*60}\n")


if __name__ == '__main__':
    main()

